version: "3"

services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  backend:
    image: docker.nasreddinebacali.info/acm-backend:latest
    environment:
      - DATABASE_URL=jdbc:mariadb://db:3306/acmdb?autoReconnect=true&useSSL=false
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=user
    links:
      - db:database
  frontend:
    image: docker.nasreddinebacali.info/acm-frontend:latest
    links:
      - backend:backend
    ports:
      - 4000:4000
